name: Clinical codelist request
description: Use to record condition/procedure/test codelists
title: '[Delete as appropriate] *CONDITION*/*PROCEDURE*/*TEST*: [TITLE]'
body: 
  - type: textarea
    attributes:
      label: User Requirements
      description: Give an idea of what the purpose of the codelist is. Is there a particular study it is to be used in? What are you hoping to identify using the codelist? Will it be used along or in combination with other codelists? Generally the more information the better.
      placeholder: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Sensitivity versus specificity
      description: If possible, give an idea of what the balance should be (e.g. I only want to identify confirmed cases of COVID-19 versus I want to identify anyone with even a potential COVID-19 symptom).
      placeholder: 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Existing relevent codelists
      description: Are you aware of any existing similar codelists? Why aren't these suitable to reuse?
      placeholder: 
    validations:
      required: false
  - type: checkboxes
    id: type
    attributes:
      label: Coding system
      description: Please select the coding system required (See this blog for further info on coding systems if needed - https://www.bennett.ox.ac.uk/blog/2023/06/an-introduction-to-clinical-codes-and-terminology-systems/.
      options:
        - label: SNOMED CT
        - label: dm+d
        - label: ICD-10
        - label: Other (please detail in User Requirements)
          required: false
  - type: checkboxes
    id: type
    attributes:
      label: Coding system
      description: Please add a label indicating the type of codelist that is required..
      options:
        - label: I have added a label
          required: true
  - type: textarea
    attributes:
      label: Search terms / synonyms
      description: Any suggested search terms / synonyms (leave blank if not sure)
      placeholder: 
    validations:
      required: false
  - type: checkboxes
    id: team
    attributes:
      label: Type
      description: Please add a label indicating the type of codelist that is required.
      options:
        - label: I have added a label
          required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please upload the completed review form by dragging and dropping the file in this box. Add any other details relevant to the review that are not in the review form.
  - type: markdown
    attributes:
      value: "**When you start a review please react to this message with :eyes:. When you have completed your review add a :thumbsup:. Once two reviews have been completed and a response has been sent to the requester, please close the issue.**"